# .github/workflows/docker-build-push.yml

name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - praveen/orchestrator-api-setup
    paths:
      - 'Dockerfile'
      - 'orchestrator/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: orchestrator:latest

    - name: Log out from Docker Hub
      if: always()
      run: docker logout docker.io
