name: Docker-Push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Info
        run: |
          node -v
          npm -v
          terraform -v

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push adapters
        uses: docker/build-push-action@v4
        with:
          context: .
          file: findr_orchestrator/orchestrator/Dockerfile
          push: true
          tags: pravnreddy429/findr_orchestrator:v1
